-- 0055_seed_saccos.sql
-- Seeds the SACCO register from:
--   SASRA, LIST OF LICENSED AND AUTHORISED SACCO SOCIETIES IN KENYA
--   FOR THE FINANCIAL YEAR ENDING 31ST DECEMBER 2026, dated 3 February 2026.
--
-- Schedule I   (176 deposit-taking)  -> licence_class = 'dt'
-- Schedule III (5 credit-only)       -> licence_class = 'credit_only', active = false
-- Schedule II  (176 non-deposit-taking, BOSA only) is NOT seeded. Those are
--              employer and institution societies and are not joinable.
--
-- common_bond is 'unknown' on every row. SASRA does not publish it. It is set
-- per SACCO as each one is confirmed against its own published terms. Rows with
-- an unknown bond are never presented as joinable.
--
-- Two county values were corrected against the source, which printed a town
-- rather than a county: Unison Sacco (printed 'Nanyuki') and Viktas Sacco
-- (printed 'Nyandarua'). Both are Laikipia. Everything else is verbatim.

insert into public.saccos
  (id, name, display_name, licence_class, sasra_licensed_until,
   common_bond, county, physical_location, postal_address, active)
values
  ('2nk-sacco', '2NK Sacco Society Ltd', '2NK Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nyeri', 'Kangaru Building, Gakere Road', 'P.O Box 12196 - 10109, Nyeri', true),
  ('acumen-dt-sacco', 'Acumen DT Sacco Society Limited', 'Acumen DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kajiado', 'Great Wide Mall, Magadi Road, Rongai', 'P.O. Box 1325 - 00200, Kajiado', true),
  ('afya-sacco', 'Afya Sacco Society Ltd', 'Afya Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Afya Centre, Tom Mboya Street, Nairobi', 'P.O Box 11607 - 00400, Nairobi', true),
  ('agrochem-sacco', 'Agrochem Sacco Society Ltd', 'Agrochem Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kisumu', 'Muhoroni Town', 'P.O Box 94 - 40107, Muhoroni', true),
  ('ainabkoi-sacco', 'Ainabkoi Sacco Society Ltd', 'Ainabkoi Sacco', 'dt', date '2026-12-31',
   'unknown', 'Uasin Gishu', 'Ainabkoi Farmers Cooperative Society Land, Eldoret, Naiberi, Timboroa Road', 'P.O Box 120 - 30101, Ainabkoi', true),
  ('airports-sacco', 'Airports Sacco Society Ltd', 'Airports Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Kenya Airports Authority Head Quarters Building', 'P.O Box 19048 - 00500, Nairobi', true),
  ('amica-sacco', 'Amica Sacco Society Ltd', 'Amica Sacco', 'dt', date '2026-12-31',
   'unknown', 'Murang''a', 'Mugama Union Building, Uhuru Road, Murang''a', 'P.O Box 816 - 10200, Murang''a', true),
  ('ammar-sacco', 'Ammar Sacco Society Ltd', 'Ammar Sacco', 'dt', date '2026-12-31',
   'unknown', 'Murang''a', 'Elica Plaza, Kwame Nkrumah Road, Thika Town', 'P.O Box 6957 - 01000, Thika', true),
  ('apstar-dt-sacco', 'Apstar DT Sacco Society Ltd', 'Apstar DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Ukulima Cooperative House, Haile Selassie Avenue, Nairobi', 'P.O Box 44071 - 00100, Nairobi', true),
  ('ardhi-sacco', 'Ardhi Sacco Society Ltd', 'Ardhi Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Survey Kenya Field Headquarters, Off Thika Road', 'P.O Box 28782 - 00200, Nairobi', true),
  ('asili-sacco', 'Asili Sacco Society Ltd', 'Asili Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Asili Co-op Centre, The Lower Ngara Road, Nairobi', 'P.O Box 49064 - 00100, Nairobi', true),
  ('azima-sacco', 'Azima Sacco Society Ltd', 'Azima Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kiambu', 'Azima Sacco Plaza, Wabera Street, Thika', 'P.O Box 1124 - 01000, Thika', true),
  ('bandari-sacco', 'Bandari Sacco Society Ltd', 'Bandari Sacco', 'dt', date '2026-12-31',
   'unknown', 'Mombasa', 'Moi Avenue, Mombasa', 'P.O Box 95011 - 80104, Mombasa', true),
  ('baraka-sacco', 'Baraka Sacco Society Ltd', 'Baraka Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nyeri', 'Station Road, Off Kiaruhiu Street, Karatina', 'P.O Box 1548 - 10101, Karatina', true),
  ('baraton-sacco', 'Baraton Sacco Society Ltd', 'Baraton Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nandi', 'University of Eastern Africa Baraton, Off Eldoret Kapsabet Road, Chepterit Junction', 'P.O Box 2500 - 30100, Eldoret', true),
  ('biashara-sacco', 'Biashara Sacco Society Ltd', 'Biashara Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nyeri', 'Biashara Sacco Building, Kimathi Way, Nyeri Town', 'P.O Box 1895 - 10100, Nyeri', true),
  ('biashara-tosha-sacco', 'Biashara Tosha Sacco Society Ltd', 'Biashara Tosha Sacco', 'dt', date '2026-12-31',
   'unknown', 'Embu', 'Gakundu F.C.S Building, Embu Kianjokoma Road, Embu', 'P.O. Box 189 - 60101, Embu', true),
  ('bingwa-sacco', 'Bingwa Sacco Society Ltd', 'Bingwa Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kirinyaga', 'Bingwa Sacco Complex, Kutus Karatina Road, Kerugoya Town', 'P.O Box 434 - 10300, Kerugoya', true),
  ('boresha-sacco', 'Boresha Sacco Society Ltd', 'Boresha Sacco', 'dt', date '2026-12-31',
   'unknown', 'Baringo', 'Teachers Plaza, Market Road, Eldama Ravine Town', 'P.O Box 80 - 20103, Eldama Ravine', true),
  ('capital-sacco', 'Capital Sacco Society Ltd', 'Capital Sacco', 'dt', date '2026-12-31',
   'unknown', 'Meru', 'Maccu Building, Kenyatta Highway, Meru', 'P.O Box 1479 - 60200, Meru', true),
  ('centenary-sacco', 'Centenary Sacco Society Ltd', 'Centenary Sacco', 'dt', date '2026-12-31',
   'unknown', 'Meru', 'Intercity Building, Meru Nanyuki Highway, Meru Town Centre', 'P.O Box 1207 - 60200, Meru', true),
  ('chai-sacco', 'Chai Sacco Society Ltd', 'Chai Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Chai House, Koinange Street, Nairobi', 'P.O Box 278 - 00200, Nairobi', true),
  ('chuka-university-sacco', 'Chuka University Sacco Society Ltd', 'Chuka University Sacco', 'dt', date '2026-12-31',
   'unknown', 'Tharaka Nithi', 'Chuka University, Students Recreation Centre, Chuka Town', 'P.O Box 109 - 60400, Chuka', true),
  ('chuna-sacco', 'Chuna Sacco Society Ltd', 'Chuna Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'University of Nairobi, Engineering Department Building, Harry Thuku Road', 'P.O Box 30197 - 00100, Nairobi', true),
  ('cosmopolitan-sacco', 'Cosmopolitan Sacco Society Ltd', 'Cosmopolitan Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nakuru', 'Natec Plaza, Kijabe Row Street, Nakuru', 'P.O Box 1931 - 20100, Nakuru', true),
  ('county-sacco', 'County Sacco Society Ltd', 'County Sacco', 'dt', date '2026-12-31',
   'unknown', 'Embu', 'County Sacco Building, Kanja Shauri Road, Kanja Town', 'P.O Box 21 - 60103, Runyenjes', true),
  ('daima-sacco', 'Daima Sacco Society Ltd', 'Daima Sacco', 'dt', date '2026-12-31',
   'unknown', 'Embu', 'Daima Sacco Building, Mutunduri Kianjokoma Road, Manyatta Market Centre', 'P.O Box 2032 - 60100, Embu', true),
  ('defence-sacco', 'Defence Sacco Society Ltd', 'Defence Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Ulinzi House, Lenana Road, Hurlingham, Nairobi', 'P.O Box 40668 - 00100, Nairobi', true),
  ('dhabiti-sacco', 'Dhabiti Sacco Society Ltd', 'Dhabiti Sacco', 'dt', date '2026-12-31',
   'unknown', 'Meru', 'Dhabiti Sacco Building, Maua Mikinduri Road, Maua Township', 'P.O Box 353 - 60600, Maua', true),
  ('dimkes-dt-sacco', 'Dimkes DT Sacco Society Ltd', 'Dimkes DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kiambu', 'Bishop Magua House, Biashara Street, Kiambu Town', 'P.O Box 886 - 00900, Kiambu', true),
  ('eco-pillar-sacco', 'Eco-Pillar Sacco Society Ltd', 'Eco-Pillar Sacco', 'dt', date '2026-12-31',
   'unknown', 'West Pokot', 'Makutano Teachers Plaza, Lotodo Street, Kapenguria Town', 'P.O Box 48 - 30600, Kapenguria', true),
  ('edis-sacco', 'Edis Sacco Society Ltd', 'Edis Sacco', 'dt', date '2026-12-31',
   'unknown', 'Bomet', 'Ngocho Building, Opposite NCPD, Ngocho, Bomet', 'P.O. Box 228 - 20400, Bomet', true),
  ('egerton-university-sacco', 'Egerton University Sacco Society Ltd', 'Egerton University Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nakuru', 'Egerton Sacco Plaza, Egerton University, Njoro Township', 'P.O Box 178 - 20115, Egerton', true),
  ('elimu-sacco', 'Elimu Sacco Society Ltd', 'Elimu Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Mubiru Road, Nairobi', 'P.O Box 10073 - 00100, Nairobi', true),
  ('enea-sacco', 'Enea Sacco Society Ltd', 'Enea Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nyeri', 'Kiangararu House, Karatina Nairobi Highway, Karatina Town', 'P.O Box 1836 - 10101, Karatina', true),
  ('faridi-sacco', 'Faridi Sacco Society Ltd', 'Faridi Sacco', 'dt', date '2026-12-31',
   'unknown', 'Busia', 'Faridi Housing Plaza, Busia Kisumu Road', 'P.O Box 448 - 50400, Busia', true),
  ('fariji-sacco', 'Fariji Sacco Society Ltd', 'Fariji Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kiambu', 'Diplomat Building, Githunguri Street, Kiambu', 'P.O. Box 589 - 00216, Githunguri', true),
  ('fortitude-sacco', 'Fortitude Sacco Society Ltd', 'Fortitude Sacco', 'dt', date '2026-12-31',
   'unknown', 'Homabay', 'Fortitude Sacco Building, Mbita Township', 'P.O Box 237 - 40205, Mbita', true),
  ('fortune-sacco', 'Fortune Sacco Society Ltd', 'Fortune Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kirinyaga', 'Fortune Plaza, Main Street, Kerugoya', 'P.O. Box 559 - 10300, Kerugoya', true),
  ('fundilima-sacco', 'Fundilima Sacco Society Ltd', 'Fundilima Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kiambu', 'Fedha House, JKUAT, Juja Town', 'P.O. Box 62000 - 00200, Nairobi', true),
  ('gdc-sacco', 'GDC Sacco Society Ltd', 'GDC Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kiambu', 'GDC Sacco Plaza, Market Street, Kiambu', 'P.O. Box 896 - 00216, Githunguri', true),
  ('golden-pillar-sacco', 'Golden Pillar Sacco Society Ltd', 'Golden Pillar Sacco', 'dt', date '2026-12-31',
   'unknown', 'Meru', 'Imenti Complex, Main Stage, Meru Town', 'P.O Box 3192 - 60200, Meru', true),
  ('good-faith-sacco', 'Good Faith Sacco Society Ltd', 'Good Faith Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kiambu', 'Nyambari Kiambu Kiwa House, Uplands Githunguri Road', 'P.O. Box 224 - 00222, Uplands', true),
  ('good-hope-sacco', 'Good Hope Sacco', 'Good Hope Sacco', 'dt', date '2026-12-31',
   'unknown', 'Narok', 'Mwalimu Plaza, Narok Kijabe Road, Narok', 'P.O Box 158 - 20500, Narok', true),
  ('goodway-sacco', 'Goodway Sacco Society Ltd', 'Goodway Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kirinyaga', 'Machere Plaza, Kerugoya Back Street, Kerugoya Town', 'P.O Box 662 - 10300, Kerugoya', true),
  ('gusii-mwalimu-sacco', 'Gusii Mwalimu Sacco Society Ltd', 'Gusii Mwalimu Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kisii', 'Mwalimu House, Kisii Kericho Road, Kisii', 'P.O Box 1335 - 40200, Kisii', true),
  ('harambee-dt-sacco', 'Harambee DT Sacco Society Ltd', 'Harambee DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Harambee Sacco Plaza, Haile Selassie Avenue, Nairobi', 'P.O Box 47815 - 00100, Nairobi', true),
  ('hazina-sacco', 'Hazina Sacco Society Ltd', 'Hazina Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Hazina Sacco Place, Ngong Road, Nairobi', 'P.O Box 59877 - 00200, Nairobi', true),
  ('home-business-sacco', 'Home Business Sacco Society Ltd', 'Home Business Sacco', 'dt', date '2026-12-31',
   'unknown', 'Laikipia', 'Tec Biz Centre, Koinange Road, Nyahururu Town', 'P.O Box 1073 - 20300, Nyahururu', true),
  ('ilkisonko-sacco', 'Ilkisonko Sacco Society', 'Ilkisonko Sacco Society', 'dt', date '2026-12-31',
   'unknown', 'Kajiado', 'Musangairo FCS Building, Loitokitok Town', 'P.O Box 91 - 00209, Loitokitok', true),
  ('imarika-sacco', 'Imarika Sacco Society Ltd', 'Imarika Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kilifi', 'Imarika Plaza, Kenyatta Road, Kilifi', 'P.O Box 712 - 80108, Kilifi', true),
  ('imarisha-sacco', 'Imarisha Sacco Society Ltd', 'Imarisha Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kericho', 'Kipsigis Teachers Cooperative House, Kisumu Nakuru Highway', 'P.O. Box 682 - 20200, Kericho', true),
  ('invest-and-grow-ig-sacco', 'Invest and Grow (IG) Sacco Society Ltd', 'Invest and Grow (IG) Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kakamega', 'Invest and Grow Plaza, Khalisia Road 3, Kakamega', 'P.O. Box 1150 - 50100, Kakamega', true),
  ('jamii-sacco', 'Jamii Sacco Society Ltd', 'Jamii Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Jamii Sacco Court, Mukenia Road, South B, Nairobi', 'P.O. Box 57929 - 00200, Nairobi', true),
  ('jamii-yetu-sacco', 'Jamii Yetu Sacco Society Ltd', 'Jamii Yetu Sacco', 'dt', date '2026-12-31',
   'unknown', 'Meru', 'Amwathi MMH Sacco Plaza, Kanuni Road, Maua', 'P.O Box 469 - 60600, Maua', true),
  ('jitegemee-sacco', 'Jitegemee Sacco Society Ltd', 'Jitegemee Sacco', 'dt', date '2026-12-31',
   'unknown', 'Mombasa', 'L.R No. 242, Msa/Block 134/XXVI, Kizingo House No.2, Kaunda Street, Mvita, Mombasa', 'P.O Box 86937 - 80100, Mombasa', true),
  ('jogoo-sacco', 'Jogoo Sacco Society Ltd', 'Jogoo Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Commodore Office Suites, Off Ngong Ring Road, Kindaruma Avenue, Nairobi', 'P.O Box 56074 - 00200, Nairobi', true),
  ('joinas-sacco', 'Joinas Sacco Society Ltd', 'Joinas Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kiambu', 'Kanja House, Limuru Banana Road, Banana Town', 'P.O Box 669 - 00219, Karuri', true),
  ('jumuika-sacco', 'Jumuika Sacco Society Ltd', 'Jumuika Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kisumu', 'Chemelil Sugar Sports Complex', 'P.O Box 14 - 40112, Awasi', true),
  ('k-pillar-sacco', 'K-Pillar Sacco Society Ltd', 'K-Pillar Sacco', 'dt', date '2026-12-31',
   'unknown', 'Bomet', 'K-Pillar Building, Bomet Litein Road, Mogogosiek', 'P.O Box 83 - 20403, Mogogosiek', true),
  ('k-unity-sacco', 'K-Unity Sacco Society Ltd', 'K-Unity Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kiambu', 'K-Unity Building, Kiambu Town', 'P.O Box 268 - 00900, Kiambu', true),
  ('kabiyet-sacco', 'Kabiyet Sacco Society Ltd', 'Kabiyet Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nandi', 'Mosoriot Kaiboi Road, Kabiyet Trading Centre', 'P.O. Box 195 - 30303, Kabiyet', true),
  ('kencream-sacco', 'Kencream Sacco Society Ltd', 'Kencream Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Creamary House, Dakar Road, Nairobi', 'P.O Box 30131 - 00100, Nairobi', true),
  ('kenpipe-sacco', 'Kenpipe Sacco Society Ltd', 'Kenpipe Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Kenpipe Plaza, Sekoni Road, Nairobi', 'P.O Box 314 - 00507, Nairobi', true),
  ('kenversity-sacco', 'Kenversity Sacco Society Ltd', 'Kenversity Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Kenversity Plaza, Kahawa Sukari Road, Nairobi', 'P.O Box 10263 - 00100, Nairobi', true),
  ('kenya-achievas-sacco', 'Kenya Achievas Sacco Society Ltd', 'Kenya Achievas Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kisii', 'Achievas Plaza, Kisii Kilgoris Road, Nyamache Town, Kisii', 'P.O Box 3080 - 40200, Kisii', true),
  ('kenya-highlands-sacco', 'Kenya Highlands Sacco Society Ltd', 'Kenya Highlands Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kericho', 'Temiik House, Kericho Kisumu Highway', 'P.O Box 2085 - 20200, Kericho', true),
  ('kenya-national-police-dt-sacco', 'Kenya National Police DT Sacco Society Ltd', 'Kenya National Police DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Kenya Police Sacco Plaza, Ngara Road, Nairobi', 'P.O Box 51042 - 00200, Nairobi', true),
  ('keystone-dt-sacco', 'Keystone DT Sacco Society Ltd', 'Keystone DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kisumu', 'Kenya Re Insurance Plaza, Bank Street, Kisumu', 'P.O. Box 2073 - 40100, Kisumu', true),
  ('kimbilio-daima-sacco', 'Kimbilio Daima Sacco Society Ltd', 'Kimbilio Daima Sacco', 'dt', date '2026-12-31',
   'unknown', 'Bomet', 'Chepsol Plaza, Kimulot Road, Kapset', 'P.O Box 81 - 20225, Kericho', true),
  ('kimisitu-sacco', 'Kimisitu Sacco Society Ltd', 'Kimisitu Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'AEA Plaza, Valley Road, Nairobi', 'P.O. Box 10454 - 00200, Nairobi', true),
  ('kingdom-sacco', 'Kingdom Sacco Society Ltd', 'Kingdom Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kiambu', 'Empower House, Githurai 45, Thika Road', 'P.O Box 8017 - 00300, Nairobi', true),
  ('kolenge-tea-sacco', 'Kolenge Tea Sacco Society Ltd', 'Kolenge Tea Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nandi', 'Nandi Hills Plaza, Nandi Hills Town', 'P.O Box 291 - 30301, Nandi Hills', true),
  ('koru-dt-sacco', 'Koru DT Sacco Society Ltd', 'Koru DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kisumu', 'Homalime Company Limited, Koru Town', 'P.O Box Private Bag - 40100, Koru', true),
  ('kumbukumbu-sacco', 'Kumbukumbu Sacco Society Ltd', 'Kumbukumbu Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'National Museum Headquarters, Museum Hill Road, Nairobi', 'P.O Box 22330 - 00400, Nairobi', true),
  ('kwetu-dt-sacco', 'Kwetu DT Sacco Society Ltd', 'Kwetu DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Machakos', 'Mwalimu Centre, Syokimau Road, Machakos Town', 'P.O Box 818 - 90100, Machakos', true),
  ('kwikas-dt-sacco', 'Kwikas DT Sacco Society Ltd', 'Kwikas DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nyandarua', 'Ndaragwa Umoja Building, Kimathi Road, Nyandarua', 'P.O Box 27 - 20306, Ndaragwa', true),
  ('lainisha-sacco', 'Lainisha Sacco Society Ltd', 'Lainisha Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kirinyaga', 'Lainisha Sacco Building, Mwea Town, Kirinyaga', 'P.O Box 272 - 10303, Wang''uru', true),
  ('lamu-teachers-sacco', 'Lamu Teachers Sacco Ltd', 'Lamu Teachers', 'dt', date '2026-12-31',
   'unknown', 'Lamu', 'L.R No 784/1, Lamu Teachers Sacco Building, Galogalo Street, Lamu', 'P.O Box 14 - 40112, Lamu', true),
  ('lengo-sacco', 'Lengo Sacco Society Ltd', 'Lengo Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kilifi', 'Standard Arcade, Mama Ngina Street, Malindi Town', 'P.O. Box 1005 - 80200, Malindi', true),
  ('mafanikio-sacco', 'Mafanikio Sacco Society Ltd', 'Mafanikio Sacco', 'dt', date '2026-12-31',
   'unknown', 'Mombasa', 'Mombasa Teachers Building, Jomo Kenyatta Avenue, Mombasa', 'P.O Box 86515 - 80100, Mombasa', true),
  ('magadi-sacco', 'Magadi Sacco Society Ltd', 'Magadi Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kajiado', 'Pam View Building, Magadi Road, Magadi Soda, Kajiado', 'P.O. Box 13 - 00205, Magadi', true),
  ('magereza-sacco', 'Magereza Sacco Society Ltd', 'Magereza Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Mageso Chambers, Moi Avenue, Nairobi', 'P.O. Box 53131 - 00200, Nairobi', true),
  ('maisha-bora-sacco', 'Maisha Bora Sacco Society Ltd', 'Maisha Bora Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Commercial Street, Industrial Area, Nairobi', 'P.O. Box 30062 - 00200, Nairobi', true),
  ('mentor-sacco', 'Mentor Sacco Society Ltd', 'Mentor Sacco', 'dt', date '2026-12-31',
   'unknown', 'Murang''a', 'Mentor Plaza, Uhuru Road, Murang''a', 'P.O Box 789 - 10200, Murang''a', true),
  ('mhasibu-dt-sacco', 'Mhasibu DT Sacco Society Ltd', 'Mhasibu DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Absa Towers, Market Street, Nairobi', 'P.O Box 31295 - 00600, Nairobi', true),
  ('mudete-sacco', 'Mudete Sacco Society Ltd', 'Mudete Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kakamega', 'Sacco Plaza, Khayega, Kakamega', 'P.O. Box 221 - 50104, Kakamega', true),
  ('muki-sacco', 'Muki Sacco Society Ltd', 'Muki Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nyandarua', 'Muki House, Ndunyu Njeru Road, Kinangop', 'P.O Box 398 - 20318, North Kinangop', true),
  ('mwalimu-national-sacco', 'Mwalimu National Sacco Society Ltd', 'Mwalimu National Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Hill Lane, Nairobi City', 'P.O. Box 62641 - 00200, Nairobi', true),
  ('mwietheri-sacco', 'Mwietheri Sacco Society Ltd', 'Mwietheri Sacco', 'dt', date '2026-12-31',
   'unknown', 'Embu', 'Rungeto F.C.S, Githure', 'P.O Box 2445 - 60100, Embu', true),
  ('mwito-sacco', 'Mwito Sacco Society Ltd', 'Mwito Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Mwito Building, Desai Road, Nairobi', 'P.O Box 56763 - 00200, Nairobi', true),
  ('nacico-sacco', 'Nacico Sacco Society Ltd', 'Nacico Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Nacico Plaza, Landhies Road, Nairobi', 'P.O Box 34525 - 00100, Nairobi', true),
  ('nafasi-dt-sacco', 'Nafasi DT Sacco Society Ltd', 'Nafasi DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'NCPB Nairobi Silos Complex, Off Outering Road, Nairobi', 'P.O. Box 41426 - 00100, Nairobi', true),
  ('nandi-farmers-sacco', 'Nandi Farmers Sacco Society Ltd', 'Nandi Farmers Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nandi', 'Nandi Hills Plaza, Market Street', 'P.O Box 333 - 30301, Nandi Hills', true),
  ('nation-dt-sacco', 'Nation DT Sacco Society Ltd', 'Nation DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Cambrian Building, Moi Avenue, Nairobi', 'P.O. Box 22022 - 00400, Nairobi', true),
  ('nawiri-sacco', 'Nawiri Sacco Society Ltd', 'Nawiri Sacco', 'dt', date '2026-12-31',
   'unknown', 'Embu', 'EMCO House, Taifa Road, Embu', 'P.O Box 400 - 60100, Embu', true),
  ('ndege-chai-sacco', 'Ndege Chai Sacco Society Ltd', 'Ndege Chai Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kericho', 'Ndege Chai House, Kericho Nakuru Highway, Kericho', 'P.O Box 857 - 20200, Kericho', true),
  ('ndosha-sacco', 'Ndosha Sacco Society Ltd', 'Ndosha Sacco', 'dt', date '2026-12-31',
   'unknown', 'Tharaka Nithi', 'L.R No. Plot 1206, Ndosha Sacco Plaza, Chogoria', 'P.O. Box 532 - 60401, Tharaka Nithi', true),
  ('new-fortis-sacco', 'New Fortis Sacco Society Ltd', 'New Fortis Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nyeri', 'New Fortis Sacco Plaza, Off Kenyatta Road, Nyeri Town', 'P.O Box 1939 - 10100, Nyeri', true),
  ('nexus-sacco', 'Nexus Sacco Society Ltd', 'Nexus Sacco', 'dt', date '2026-12-31',
   'unknown', 'Meru', 'Kathera House, Kamunara, Nkubu, Meru', 'P.O. Box 251 - 60202, Nkubu', true),
  ('ngarisha-sacco', 'Ng''arisha Sacco Society Ltd', 'Ng''arisha Sacco', 'dt', date '2026-12-31',
   'unknown', 'Bungoma', 'Bungoma Teachers Plaza, Bungoma', 'P.O. Box 1199 - 50200, Bungoma', true),
  ('njiwa-sacco', 'Njiwa Sacco Society Ltd', 'Njiwa Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Golf View Office Suites, Wambui Road, Nairobi', 'P.O Box 10221 - 00100, Nairobi', true),
  ('nrs-sacco', 'NRS Sacco Society Ltd', 'NRS Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kiambu', 'Ondiri Building, Kikuyu Road, Kikuyu', 'P.O Box 575 - 00902, Kikuyu', true),
  ('nssf-sacco', 'NSSF Sacco Society Ltd', 'NSSF Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Social Security House, Bishops Road, Nairobi', 'P.O Box 43338 - 00100, Nairobi', true),
  ('nyambene-arimi-sacco', 'Nyambene Arimi Sacco Society Ltd', 'Nyambene Arimi Sacco', 'dt', date '2026-12-31',
   'unknown', 'Meru', 'Nyambene Arimi Sacco Plaza, Maua Kanuni Road, Meru Town', 'P.O Box 493 - 60600, Maua', true),
  ('nyati-sacco', 'Nyati Sacco Society Ltd', 'Nyati Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Nyati Sacco Plaza, Nairobi West, Nairobi', 'P.O Box 7601 - 00200, Nairobi', true),
  ('ollin-sacco', 'Ollin Sacco Society Ltd', 'Ollin Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kirinyaga', 'Ollin Sacco Building, Off Karatina Kutus Road, Kerugoya', 'P.O Box 83 - 10300, Kerugoya', true),
  ('orient-sacco', 'Orient Sacco Society Ltd', 'Orient Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kiambu', 'Wakibe Building, Thika Section 9 OAU Road, Thika Town', 'P.O Box 1842 - 01000, Thika', true),
  ('patnas-sacco', 'Patnas Sacco Society Ltd', 'Patnas Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kericho', 'Litein Town, Patnas Plaza, Kericho Sotik Road', 'P.O. Box 601 - 20210, Litein', true),
  ('ports-dt-sacco', 'Ports DT Sacco Society Ltd', 'Ports DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Mombasa', 'Mombasa Port Sacco Plaza, Mwakilingo Road', 'P.O Box 95372 - 80104, Mombasa', true),
  ('prime-time-sacco', 'Prime-Time Sacco Society Ltd', 'Prime-Time Sacco', 'dt', date '2026-12-31',
   'unknown', 'Elgeyo Marakwet', 'Mwalimu Plaza Building, Eldoret Kabarnet Road, Iten', 'P.O Box 512 - 30700, Iten', true),
  ('puan-sacco', 'Puan Sacco Society Ltd', 'Puan Sacco', 'dt', date '2026-12-31',
   'unknown', 'Narok', 'Farmers Building, Narok Nakuru Road, Narok Town', 'P.O Box 404 - 20500, Narok', true),
  ('qona-sacco', 'Qona Sacco Society Ltd', 'Qona Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Safaricom Care Centre, Waiyaki Way, Westlands, Nairobi', 'P.O Box 6682 - 00800, Nairobi', true),
  ('qwetu-sacco', 'Qwetu Sacco Society Ltd', 'Qwetu Sacco', 'dt', date '2026-12-31',
   'unknown', 'Taita Taveta', 'Qwetu Sacco Plaza, Voi Town', 'P.O Box 1186 - 80304, Voi', true),
  ('setyon-dt-sacco', 'Setyon DT Sacco Society Ltd', 'Setyon DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kericho', 'Brooke Centre, Kericho', 'P.O Box 1314 - 20200, Kericho', true),
  ('sheria-sacco', 'Sheria Sacco Society Ltd', 'Sheria Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Matumbato Close, Nairobi', 'P.O. Box 34390 - 00100, Nairobi', true),
  ('shirika-dt-sacco', 'Shirika DT Sacco Society Ltd', 'Shirika DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Shirika Coop House, Ngara Kipande Road, Ngara, Nairobi', 'P.O Box 43429 - 00100, Nairobi', true),
  ('shoppers-sacco', 'Shoppers Sacco Society Ltd', 'Shoppers Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Nature House, Tom Mboya Street', 'P.O Box 16 - 00507, Nairobi', true),
  ('simba-chai-sacco', 'Simba Chai Sacco Society Ltd', 'Simba Chai Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kericho', 'Kericho Nakuru Highway, Kericho', 'P.O. Box 977 - 20200, Kericho', true),
  ('siraji-sacco', 'Siraji Sacco Society Ltd', 'Siraji Sacco', 'dt', date '2026-12-31',
   'unknown', 'Meru', 'Siraji Sacco Plaza, Nanyuki Meru Highway, Timau Town', 'P.O Box Private Bag', true),
  ('skyline-dt-sacco', 'Skyline DT Sacco Society Ltd', 'Skyline DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Baringo', 'Skyrise Plaza, Eldama Ravine Eldoret Road, Eldama Ravine', 'P.O Box 660 - 20103, Eldama Ravine', true),
  ('smart-champions-sacco', 'Smart Champions Sacco Society', 'Smart Champions Sacco Society', 'dt', date '2026-12-31',
   'unknown', 'Meru', 'Muranene Building, Githongo Trading Centre, Meru', 'P.O Box 64 - 60205, Githongo', true),
  ('smartlife-sacco', 'Smartlife Sacco Society Ltd', 'Smartlife Sacco', 'dt', date '2026-12-31',
   'unknown', 'Elgeyo Marakwet', 'Marakwet Teachers Plaza, Kapsowar', 'P.O Box 118 - 30705, Kapsowar', true),
  ('solution-sacco', 'Solution Sacco Society Ltd', 'Solution Sacco', 'dt', date '2026-12-31',
   'unknown', 'Meru', 'Meru Mwalimu Plaza, Gakoromone Road, Meru', 'P.O. Box 1694 - 60200, Meru', true),
  ('sotico-sacco', 'Sotico Sacco Society Ltd', 'Sotico Sacco', 'dt', date '2026-12-31',
   'unknown', 'Bomet', 'Amotek Estate, Sotik Town', 'P.O. Box 959 - 20406, Sotik', true),
  ('southern-star-sacco', 'Southern Star Sacco Society Ltd', 'Southern Star Sacco', 'dt', date '2026-12-31',
   'unknown', 'Tharaka Nithi', 'Mt Building, Chuka Town', 'P.O Box 514 - 60400, Chuka', true),
  ('stake-kenya-sacco', 'Stake Kenya Sacco Society Ltd', 'Stake Kenya Sacco', 'dt', date '2026-12-31',
   'unknown', 'Migori', 'Stake Kenya Sacco Plaza, Migori Kehancha Ntimaru Road, Kehancha Town', 'P.O Box 208 - 40413, Kehancha', true),
  ('stawisha-sacco', 'Stawisha Sacco Society Ltd', 'Stawisha Sacco', 'dt', date '2026-12-31',
   'unknown', 'Bungoma', 'Mwalimu Plaza, Kapsokwony Kaptama Road, Kapsokwony', 'P.O Box 27 - 50203, Kapsokwony', true),
  ('stima-dt-sacco', 'Stima DT Sacco Society Ltd', 'Stima DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Stima Sacco Plaza, Mushembi Road, Parklands, Nairobi', 'P.O Box 75629 - 00200, Nairobi', true),
  ('strategic-dt-sacco', 'Strategic DT Sacco Society Ltd', 'Strategic DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Lunga Lunga Square, Industrial Area, Nairobi', 'P.O. Box 78506 - 00507, Nairobi', true),
  ('suluhu-sacco', 'Suluhu Sacco Society Ltd', 'Suluhu Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kitui', 'Suluhu Sacco Plaza, Kyuso Road, Mwingi', 'P.O Box 489 - 90400, Mwingi', true),
  ('supa-sacco', 'Supa Sacco Society Ltd', 'Supa Sacco', 'dt', date '2026-12-31',
   'unknown', 'Samburu', 'Supa Plaza, Posta Road, Maralal', 'P.O. Box 271 - 20600, Maralal', true),
  ('tabasamu-sacco', 'Tabasamu Sacco Society Ltd', 'Tabasamu Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kwale', 'Tunawiri House, Kinango Road, Kwale', 'P.O Box 123 - 80403, Kwale', true),
  ('tabasuri-dt-sacco', 'Tabasuri DT Sacco Society Ltd', 'Tabasuri DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Mombasa', 'Texas Plaza, Off Fidel Odinga Road, Mombasa', 'P.O Box 80862 - 80100, Mombasa', true),
  ('tai-sacco', 'Tai Sacco Society Ltd', 'Tai Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kiambu', 'Tai Plaza, Githunguri Town, Kiambu', 'P.O Box 718 - 00216, Githunguri', true),
  ('taifa-sacco', 'Taifa Sacco Society Ltd', 'Taifa Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nyeri', 'NCU Building, Gakere Road, Nyeri Town', 'P.O Box 649 - 10100, Nyeri', true),
  ('taqwa-sacco', 'Taqwa Sacco Society Ltd', 'Taqwa Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Jamia Plaza, Kigali Street, Nairobi', 'P.O Box 10180 - 00100, Nairobi', true),
  ('taraji-sacco', 'Taraji Sacco Society Ltd', 'Taraji Sacco', 'dt', date '2026-12-31',
   'unknown', 'Siaya', 'Mwalimu Plaza, Oginga Odinga Street, Siaya', 'P.O. Box 605 - 40600, Siaya', true),
  ('telepost-sacco', 'Telepost Sacco Society Ltd', 'Telepost Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'City Square Post Office, Haile Selassie Avenue, Nairobi', 'P.O Box 49557 - 00100, Nairobi', true),
  ('tembo-sacco', 'Tembo Sacco Society Ltd', 'Tembo Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Tembo Sacco Complex, Garden Estate Road, Mukima Drive, Nairobi', 'P.O Box 91 - 00618, Ruaraka', true),
  ('tenhos-sacco', 'Tenhos Sacco Society Ltd', 'Tenhos Sacco', 'dt', date '2026-12-31',
   'unknown', 'Bomet', 'Tenhos Building, Tenwek, Bomet', 'P.O Box 391 - 20400, Bomet', true),
  ('thamani-sacco', 'Thamani Sacco Society Ltd', 'Thamani Sacco', 'dt', date '2026-12-31',
   'unknown', 'Tharaka Nithi', 'Thamani House, Chuka Town', 'P.O. Box 467 - 60400, Chuka', true),
  ('the-apple-sacco', 'The Apple Sacco Society Ltd', 'The Apple Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nandi', 'Tasccos House, Kapsabet Chavakali Road, Kapsabet', 'P.O. Box 153 - 50305, Kaimosi', true),
  ('the-kenya-bankers-sacco', 'The Kenya Bankers Sacco Society Ltd', 'The Kenya Bankers Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'The Kenya Bankers Sacco Centre, 3rd Ngong Avenue, Nairobi', 'P.O. Box 73236 - 00200, Nairobi', true),
  ('the-noble-sacco', 'The Noble Sacco Society Ltd', 'The Noble Sacco', 'dt', date '2026-12-31',
   'unknown', 'Uasin Gishu', 'The Noble Sacco Building, Ronald Ngala Road, Eldoret Town', 'P.O Box 3466 - 30100, Eldoret', true),
  ('times-u-sacco', 'Times U Sacco Society Ltd', 'Times U Sacco', 'dt', date '2026-12-31',
   'unknown', 'Meru', 'Nkubu, KCB Road, Nkubu', 'P.O Box 310 - 60202, Nkubu', true),
  ('topkrim-dt-sacco', 'Topkrim DT Sacco Society Ltd', 'Topkrim DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Homabay', 'Kisumu Kisii Road, Oyugis Town, Homabay', 'P.O Box 127 - 40222, Oyugis', true),
  ('tower-sacco', 'Tower Sacco Society Ltd', 'Tower Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nyandarua', 'Tower Sacco Fosa Building, Ol Kalou Township', 'P.O Box 259 - 20303, Ol Kalou', true),
  ('trans-counties-sacco', 'Trans-Counties Sacco Society Ltd', 'Trans-Counties Sacco', 'dt', date '2026-12-31',
   'unknown', 'Trans Nzoia', 'Kapsara, Trans-Counties Sacco Office, Kapsara', 'P.O Box 2965 - 30200, Kitale', true),
  ('trans-national-times-sacco', 'Trans-National Times Sacco Society Ltd', 'Trans-National Times Sacco', 'dt', date '2026-12-31',
   'unknown', 'Trans Nzoia', 'Kitale Teachers Plaza, KANU Street, Kitale', 'P.O. Box 2274 - 30200, Kitale', true),
  ('trans-elite-county-sacco', 'Trans Elite County Sacco Society Ltd', 'Trans Elite County Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nandi', 'Former Barclays Bank Building, Kapsabet Chavakali Road, Kapsabet Town', 'P.O Box 547 - 30300, Kapsabet', true),
  ('trans-nation-sacco', 'Trans Nation Sacco Society Ltd', 'Trans Nation Sacco', 'dt', date '2026-12-31',
   'unknown', 'Tharaka Nithi', 'Mwalimu Centre, DC Road, Chuka Town', 'P.O Box 15 - 60400, Chuka', true),
  ('ufanisi-dt-sacco', 'Ufanisi DT Sacco Society Ltd', 'Ufanisi DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Development House, Moi Avenue, Nairobi', 'P.O. Box 2973 - 00200, Nairobi', true),
  ('ukristo-na-ufanisi-dt-sacco', 'Ukristo Na Ufanisi DT Sacco Society Ltd', 'Ukristo Na Ufanisi DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'ACK Emmanuel Church Riruta, Nairobi', 'P.O Box 872 - 00605, Nairobi', true),
  ('unaitas-sacco', 'Unaitas Sacco Society Ltd', 'Unaitas Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Cardinal Otunga Plaza, Nairobi', 'P.O Box 38721 - 00100, Nairobi', true),
  ('uni-county-sacco', 'Uni-County Sacco Society Ltd', 'Uni-County Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nakuru', 'Nakuru Municipality Block 9/37, Generation House, Kijabe Row, Nakuru', 'P.O. Box 10132 - 20100, Nakuru', true),
  ('unison-sacco', 'Unison Sacco Society Ltd', 'Unison Sacco', 'dt', date '2026-12-31',
   'unknown', 'Laikipia', 'Unison Plaza, Nyeri Nanyuki Road, Nanyuki Municipality', 'P.O. Box 414 - 10400, Nanyuki', true),
  ('united-nations-dt-sacco', 'United Nations DT Sacco Society Ltd', 'United Nations DT Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'United Nations Complex, United Nations Avenue, Nairobi', 'P.O Box 2210 - 00621, Nairobi', true),
  ('united-winners-sacco', 'United Winners Sacco Society', 'United Winners Sacco Society', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'UWS Plaza, 1st Floor, Spine Road, Nairobi', 'P.O Box 1390 - 00515, Westlands', true),
  ('universal-traders-sacco', 'Universal Traders Sacco Society Ltd', 'Universal Traders Sacco', 'dt', date '2026-12-31',
   'unknown', 'Machakos', 'Traders House, Syokimau Road, Machakos', 'P.O Box 2119 - 90100, Machakos', true),
  ('univision-sacco', 'Univision Sacco Society Ltd', 'Univision Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kitui', 'Teachers Plaza, Kitui Town', 'P.O. Box 254 - 90200, Kitui', true),
  ('ushuru-sacco', 'Ushuru Sacco Society Ltd', 'Ushuru Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Ushuru Sacco Centre, Wood Avenue, Kilimani', 'P.O Box 52072 - 00200, Nairobi', true),
  ('vihiga-county-farmers-sacco', 'Vihiga County Farmers Sacco Society Ltd', 'Vihiga County Farmers Sacco', 'dt', date '2026-12-31',
   'unknown', 'Vihiga', 'Mudete Town, Vihiga County', 'P.O Box 309 - 50317, Chavakali', true),
  ('viktas-sacco', 'Viktas Sacco Society Ltd', 'Viktas Sacco', 'dt', date '2026-12-31',
   'unknown', 'Laikipia', 'Glanin Centre, Nyahururu Nyeri Road, Mairo Inya, Nyandarua', 'P.O. Box 2183, Nyahururu', true),
  ('vision-afrika-sacco', 'Vision Afrika Sacco Society Ltd', 'Vision Afrika Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nakuru', 'Rajdeep House, Kenyatta Avenue, Nakuru', 'P.O Box 18263 - 20100, Nakuru', true),
  ('vision-point-sacco', 'Vision Point Sacco Society Ltd', 'Vision Point Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kisii', 'Borabu Farmers Union Building, Keroka Sotik Highway, Borabu', 'P.O. Box 42 - 40502, Nyansiongo', true),
  ('wakenya-pamoja-sacco', 'Wakenya Pamoja Sacco Society Ltd', 'Wakenya Pamoja Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kisii', 'Kahawa House, Kisii Keroka Road, Kisii', 'P.O. Box 829 - 40200, Kisii', true),
  ('wakulima-commercial-sacco', 'Wakulima Commercial Sacco Society Ltd', 'Wakulima Commercial Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nyeri', 'MWD Limited Complex, Mukurweini Nyeri Road, Mukurweini Town', 'P.O. Box 232 - 10103, Mukurweini', true),
  ('wanaanga-sacco', 'Wanaanga Sacco Society Ltd', 'Wanaanga Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Kenya Meteorological Department, Ngong Road, Dagoretti', 'P.O Box 34680 - 00100, Nairobi', true),
  ('wananchi-sacco', 'Wananchi Sacco Society Ltd', 'Wananchi Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nyeri', 'Wananchi Building, Othaya', 'P.O Box 910 - 10106, Othaya', true),
  ('wanandege-sacco', 'Wanandege Sacco Society Ltd', 'Wanandege Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Wanandege Plaza, Old North Airport Road, Nairobi', 'P.O Box 19074 - 00501, Nairobi', true),
  ('washa-sacco', 'Washa Sacco Society Ltd', 'Washa Sacco', 'dt', date '2026-12-31',
   'unknown', 'Mombasa', 'Ralli House, Nyerere Avenue, Mombasa', 'P.O. Box 83256 - 80100, Mombasa', true),
  ('waumini-sacco', 'Waumini Sacco Society Ltd', 'Waumini Sacco', 'dt', date '2026-12-31',
   'unknown', 'Nairobi', 'Applewood Adams 2nd Floor, Ngong Road, Nairobi', 'P.O Box 66121 - 00800, Nairobi', true),
  ('wevarsity-sacco', 'Wevarsity Sacco Society Ltd', 'Wevarsity Sacco', 'dt', date '2026-12-31',
   'unknown', 'Kakamega', 'Wevarsity Plaza, Kakamega Webuye Road, Kakamega', 'P.O. Box 873 - 50100, Kakamega', true),
  ('winas-sacco', 'Winas Sacco Society Ltd', 'Winas Sacco', 'dt', date '2026-12-31',
   'unknown', 'Embu', 'Winas House, Embu Township', 'P.O. Box 696 - 60100, Embu', true),
  ('yetu-sacco', 'Yetu Sacco Society Ltd', 'Yetu Sacco', 'dt', date '2026-12-31',
   'unknown', 'Meru', 'Yetu Sacco Building, Nkubu Town, Meru', 'P.O Box 511 - 60202, Nkubu', true),
  ('dumisha-sacco', 'Dumisha Sacco Society Ltd', 'Dumisha Sacco', 'credit_only', date '2026-12-31',
   'unknown', 'Samburu', 'Dumisha Sacco Plaza, Maralal Town', 'P.O Box 84 - 20600, Maralal', false),
  ('bi-high-sacco', 'Bi-High Sacco Society Ltd', 'Bi-High Sacco', 'credit_only', date '2026-12-31',
   'unknown', 'Marsabit', 'Marsabit Teachers Plaza, Marsabit Town', 'P.O Box 90 - 60500, Marsabit', false),
  ('metropolitan-national-sacco', 'Metropolitan National Sacco Society Ltd', 'Metropolitan National Sacco', 'credit_only', date '2026-12-31',
   'unknown', 'Kiambu', 'Metropolitan National Sacco Building, Kiambu Town', 'P.O Box 871 - 00900, Kiambu', false),
  ('ol-kaunsel-regulated-non-wdt-sacco', 'Ol Kaunsel Regulated Non-WDT Sacco Society Ltd', 'Ol Kaunsel Regulated Non-WDT Sacco', 'credit_only', date '2026-12-31',
   'unknown', 'Kajiado', 'Kajiado County Assembly Offices, Kajiado Town', 'P.O Box 540 - 01100, Kajiado', false),
  ('digital-media-regulated-non-wdt-sacco', 'Digital Media Regulated Non-WDT Sacco Society Ltd', 'Digital Media Regulated Non-WDT Sacco', 'credit_only', date '2026-12-31',
   'unknown', 'Nairobi', 'Red Commercial Complex, 2nd Floor, Mombasa Road, Nairobi', 'P.O Box 69825 - 00400, Nairobi', false)
on conflict (id) do update set
  name                 = excluded.name,
  display_name         = excluded.display_name,
  licence_class        = excluded.licence_class,
  sasra_licensed_until = excluded.sasra_licensed_until,
  county               = excluded.county,
  physical_location    = excluded.physical_location,
  postal_address       = excluded.postal_address,
  active               = excluded.active;

-- Deliberately NOT touched on conflict: common_bond, bond_note, website, phone,
-- email, logo_url, brand_color, tier, and every joining-terms and institution
-- column. Those are researched by hand and must survive a re-run of the annual
-- register import.
